# Generated by Django 5.0.4 on 2024-05-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeVerify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='step',
        ),
    ]
