# Generated by Django 5.0.4 on 2024-05-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_codeverify_remove_user_auth_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
